// <auto-generated />
namespace MovieRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpadeDOBinCustomerClassNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpadeDOBinCustomerClassNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201807161506197_Upade DOB in Customer Class Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
